/**
 * Module Name: fahp-engine.js
 * Purpose: Independent Fuzzy Analytic Hierarchy Process (FAHP) engine for
 *          AMSESHI's two-level criteria-to-alternatives decision hierarchy.
 *
 * Methodological assumption for Phase C:
 * - Buckley-style fuzzy geometric mean priority derivation for positive
 *   triangular fuzzy reciprocal matrices.
 * - Triangular fuzzy number (TFN) scale: (1,1,1), (1,2,3), (2,3,4),
 *   (3,4,5), (4,5,6), (5,6,7), (6,7,8), (7,8,9), (9,9,9).
 * - Positive-TFN arithmetic is componentwise: multiplication, positive
 *   exponentiation, and reciprocal (1/u, 1/m, 1/l).
 * - Fuzzy priorities are defuzzified by the centroid/centre-of-gravity
 *   formula (l + m + u) / 3, then normalized to sum to one.
 *
 * This engine is intentionally independent. It does not import, call, modify,
 * or reproduce code from js/core/ahp-engine.js.
 */

export const FAHP_METHOD_ID = 'fahp';

/**
 * Standard nine-point TFN scale selected for Phase C. The current AMSESHI UI
 * already collects Saaty-style values 1–9, so this mapping permits the same
 * hierarchy and pairwise judgments to be evaluated under fuzzy uncertainty.
 */
export const TFN_LINGUISTIC_SCALE = Object.freeze({
  1: Object.freeze({ lower: 1, modal: 1, upper: 1, label: 'Equal importance' }),
  2: Object.freeze({ lower: 1, modal: 2, upper: 3, label: 'Between equal and moderate importance' }),
  3: Object.freeze({ lower: 2, modal: 3, upper: 4, label: 'Moderate importance' }),
  4: Object.freeze({ lower: 3, modal: 4, upper: 5, label: 'Between moderate and strong importance' }),
  5: Object.freeze({ lower: 4, modal: 5, upper: 6, label: 'Strong importance' }),
  6: Object.freeze({ lower: 5, modal: 6, upper: 7, label: 'Between strong and very strong importance' }),
  7: Object.freeze({ lower: 6, modal: 7, upper: 8, label: 'Very strong importance' }),
  8: Object.freeze({ lower: 7, modal: 8, upper: 9, label: 'Between very strong and extreme importance' }),
  9: Object.freeze({ lower: 9, modal: 9, upper: 9, label: 'Extreme importance' }),
});

const EPSILON = 1e-12;

/** @returns {{lower: number, modal: number, upper: number}} */
export function createTFN(lower, modal, upper) {
  const values = [lower, modal, upper];
  if (!values.every((value) => Number.isFinite(value) && value > 0)) {
    throw new TypeError('A TFN must contain finite positive lower, modal, and upper values.');
  }
  if (lower > modal || modal > upper) {
    throw new RangeError('A TFN must satisfy lower <= modal <= upper.');
  }
  return { lower, modal, upper };
}

/** @returns {{lower: number, modal: number, upper: number}} */
export function cloneTFN(tfn) {
  return createTFN(tfn.lower, tfn.modal, tfn.upper);
}

export function fuzzyMultiply(left, right) {
  return createTFN(
    left.lower * right.lower,
    left.modal * right.modal,
    left.upper * right.upper
  );
}

export function fuzzyPower(tfn, exponent) {
  if (!Number.isFinite(exponent) || exponent <= 0) {
    throw new TypeError('A positive finite exponent is required for a positive TFN.');
  }
  return createTFN(
    Math.pow(tfn.lower, exponent),
    Math.pow(tfn.modal, exponent),
    Math.pow(tfn.upper, exponent)
  );
}

/**
 * Fuzzy reciprocal of a positive triangular fuzzy number:
 * (l, m, u)^-1 = (1/u, 1/m, 1/l).
 */
export function fuzzyReciprocal(tfn) {
  return createTFN(1 / tfn.upper, 1 / tfn.modal, 1 / tfn.lower);
}

export function fuzzyAdd(left, right) {
  return createTFN(
    left.lower + right.lower,
    left.modal + right.modal,
    left.upper + right.upper
  );
}

export function sumTFNs(tfns) {
  if (!Array.isArray(tfns) || tfns.length === 0) {
    throw new TypeError('At least one TFN is required for fuzzy aggregation.');
  }
  return tfns.reduce((sum, tfn) => fuzzyAdd(sum, tfn), createTFN(EPSILON, EPSILON, EPSILON));
}

/**
 * Converts an existing crisp Saaty-scale matrix value into a TFN. Values
 * below one are treated as reciprocals of the nearest valid Saaty integer,
 * preserving the reciprocal semantics generated by the current UI.
 */
export function crispJudgmentToTFN(value) {
  if (!Number.isFinite(value) || value <= 0) {
    throw new TypeError('FAHP pairwise judgments must be finite positive numbers.');
  }

  if (value >= 1) {
    const intensity = Math.round(value);
    const scaleTFN = TFN_LINGUISTIC_SCALE[intensity];
    // The existing UI displays reciprocal values to three decimal places;
    // e.g. 0.333 can re-enter a derived matrix as 3.003. Accept that
    // established display precision while rejecting non-Saaty judgments.
    if (!scaleTFN || Math.abs(value - intensity) > 0.01) {
      throw new RangeError(`FAHP supports the current Saaty judgments 1–9; received ${value}.`);
    }
    return cloneTFN(scaleTFN);
  }

  const reciprocalIntensity = Math.round(1 / value);
  const scaleTFN = TFN_LINGUISTIC_SCALE[reciprocalIntensity];
  if (!scaleTFN || Math.abs(value - (1 / reciprocalIntensity)) > 0.006) {
    throw new RangeError(`FAHP supports reciprocals of Saaty judgments 1–9; received ${value}.`);
  }
  return fuzzyReciprocal(scaleTFN);
}

/**
 * Creates the positive fuzzy reciprocal comparison matrix corresponding to a
 * current AMSESHI crisp pairwise matrix. Diagonal entries are always (1,1,1).
 */
export function buildFuzzyComparisonMatrix(crispMatrix) {
  if (!Array.isArray(crispMatrix) || crispMatrix.length === 0) {
    throw new TypeError('A non-empty pairwise comparison matrix is required.');
  }

  const n = crispMatrix.length;
  if (!crispMatrix.every((row) => Array.isArray(row) && row.length === n)) {
    throw new TypeError('FAHP pairwise matrices must be square.');
  }

  return crispMatrix.map((row, i) => row.map((value, j) => {
    if (i === j) return cloneTFN(TFN_LINGUISTIC_SCALE[1]);
    return crispJudgmentToTFN(value);
  }));
}

/**
 * Aggregates equivalent fuzzy judgments from multiple decision makers through
 * componentwise geometric means. A single-user AMSESHI assessment does not
 * call this function, but it provides an explicit future group-decision
 * aggregation rule without changing the core priority algorithm.
 */
export function aggregateFuzzyJudgments(tfns) {
  if (!Array.isArray(tfns) || tfns.length === 0) {
    throw new TypeError('At least one TFN is required for aggregation.');
  }
  const product = tfns.reduce((accumulator, tfn) => fuzzyMultiply(accumulator, tfn), createTFN(1, 1, 1));
  return fuzzyPower(product, 1 / tfns.length);
}

/**
 * Computes each row's fuzzy geometric mean:
 * r_i = (product_j a_ij)^(1/n).
 */
export function calculateFuzzyGeometricMeans(fuzzyMatrix) {
  const n = fuzzyMatrix.length;
  return fuzzyMatrix.map((row) => {
    const product = row.reduce((accumulator, tfn) => fuzzyMultiply(accumulator, tfn), createTFN(1, 1, 1));
    return fuzzyPower(product, 1 / n);
  });
}

/**
 * Computes normalized fuzzy weights using the Buckley geometric-mean rule:
 * w_i = r_i ⊗ (sum_i r_i)^-1.
 */
export function calculateFuzzyWeights(fuzzyGeometricMeans) {
  const aggregate = sumTFNs(fuzzyGeometricMeans);
  const aggregateInverse = fuzzyReciprocal(aggregate);
  return fuzzyGeometricMeans.map((geometricMean) => fuzzyMultiply(geometricMean, aggregateInverse));
}

/** Centroid / centre-of-gravity defuzzification: (l + m + u) / 3. */
export function defuzzifyTFN(tfn) {
  return (tfn.lower + tfn.modal + tfn.upper) / 3;
}

export function normalizeWeights(weights) {
  if (!Array.isArray(weights) || weights.length === 0 || !weights.every((weight) => Number.isFinite(weight) && weight >= 0)) {
    throw new TypeError('A non-empty array of finite non-negative weights is required.');
  }
  const total = weights.reduce((sum, weight) => sum + weight, 0);
  if (total <= EPSILON) {
    throw new RangeError('Weights must sum to a positive value before normalization.');
  }
  return weights.map((weight) => weight / total);
}

/**
 * Calculates a complete FAHP priority result for one pairwise matrix, exposing
 * the fuzzy comparison matrix, geometric means, fuzzy weights, defuzzified
 * values, and normalized crisp priority vector for reproducible validation.
 */
export function calculateFuzzyPriority(crispMatrix) {
  const fuzzyMatrix = buildFuzzyComparisonMatrix(crispMatrix);
  const fuzzyGeometricMeans = calculateFuzzyGeometricMeans(fuzzyMatrix);
  const fuzzyWeights = calculateFuzzyWeights(fuzzyGeometricMeans);
  const defuzzifiedWeights = fuzzyWeights.map(defuzzifyTFN);
  const normalizedWeights = normalizeWeights(defuzzifiedWeights);

  return {
    fuzzyMatrix,
    fuzzyGeometricMeans,
    fuzzyWeights,
    defuzzifiedWeights,
    normalizedWeights,
  };
}

export function rankScores(labels, scores) {
  return labels
    .map((label, index) => ({ label, score: scores[index] }))
    .sort((left, right) => right.score - left.score)
    .map((entry, index) => ({ ...entry, rank: index + 1 }));
}

/**
 * Runs FAHP for the same two-level hierarchy accepted by the current AHP
 * workflow. Criteria and local alternative priorities are derived
 * independently from their fuzzy pairwise matrices; normalized local priorities
 * are propagated through normalized criteria weights to final alternative
 * scores and ranks.
 */
export function calculateFAHP(items, criteria, alternativeMatrices, criteriaMatrix) {
  if (!Array.isArray(items) || items.length < 2) {
    throw new TypeError('FAHP requires at least two alternatives.');
  }
  if (!Array.isArray(criteria) || criteria.length < 2) {
    throw new TypeError('FAHP requires at least two criteria.');
  }
  if (!Array.isArray(alternativeMatrices) || alternativeMatrices.length !== criteria.length) {
    throw new TypeError('FAHP requires one alternative pairwise matrix per criterion.');
  }

  const criteriaPriority = calculateFuzzyPriority(criteriaMatrix);
  const criteriaWeights = criteriaPriority.normalizedWeights;
  const alternativePriorities = alternativeMatrices.map((matrix) => calculateFuzzyPriority(matrix));
  const localPriorityVectors = alternativePriorities.map((priority) => priority.normalizedWeights);

  const rawScores = items.map((_, alternativeIndex) => criteriaWeights.reduce(
    (sum, criterionWeight, criterionIndex) => sum + criterionWeight * localPriorityVectors[criterionIndex][alternativeIndex],
    0
  ));
  const finalScores = normalizeWeights(rawScores);
  const ranking = rankScores(items, finalScores);

  return {
    criteria: {
      labels: criteria,
      weights: criteriaWeights,
      normalizedWeights: criteriaWeights,
      fuzzyWeights: criteriaPriority.fuzzyWeights,
      defuzzifiedWeights: criteriaPriority.defuzzifiedWeights,
    },
    alternatives: {
      labels: items,
      scores: finalScores,
      rawScores,
      prioritiesByCriterion: localPriorityVectors,
      fuzzyPrioritiesByCriterion: alternativePriorities.map((priority) => priority.fuzzyWeights),
      defuzzifiedPrioritiesByCriterion: alternativePriorities.map((priority) => priority.defuzzifiedWeights),
      ranking,
    },
    consistency: {
      criteriaCR: null,
      alternativeCRs: alternativeMatrices.map(() => null),
      overallCR: null,
      status: 'not-applicable',
      explanation: 'No fuzzy consistency index is claimed by this Buckley-style FAHP implementation. The parallel AHP result retains its validated Saaty consistency ratios.',
    },
    intermediate: {
      tfnScale: TFN_LINGUISTIC_SCALE,
      criteria: criteriaPriority,
      alternatives: alternativePriorities,
    },
    metadata: {
      calculationMethod: 'fahp-buckley-fuzzy-geometric-mean',
      fuzzyNumberType: 'triangular-fuzzy-number',
      tfnScale: 'nine-point-symmetric-tfn-scale',
      aggregationMethod: 'row-fuzzy-geometric-mean',
      defuzzificationMethod: 'centroid-centre-of-gravity',
      normalizationMethod: 'sum-normalization-after-defuzzification',
      timestamp: new Date().toISOString(),
    },
  };
}
